"""The item catalog — single source of truth for gear stats and art keys.

Both the asset generator (``scripts/generate_assets.py``) and the database
seeder import this module, which guarantees ``items.layer_key`` always matches
an actual PNG on disk.  Stats are deliberately small: Drip matters mostly for
Heist luck and shop discounts, ATK/DEF for duels and raids.
"""

from __future__ import annotations

from dataclasses import dataclass

from models.enums import Rarity, Slot


@dataclass(frozen=True, slots=True)
class ItemDef:
    """Static definition of one equippable item."""

    id: str
    name: str
    slot: Slot
    rarity: Rarity
    atk: int = 0
    defense: int = 0
    drip: int = 0
    price_credits: int = 0
    price_soul_shards: int = 0
    description: str = ""
    shop_pool: str = "rotating"  # rotating | permanent | starter

    @property
    def layer_key(self) -> str:
        """PNG basename; matches the file the asset generator writes."""
        return self.id

    @property
    def folder(self) -> str:
        """Layer folder under ``assets/layers/`` for this slot."""
        from models.enums import SLOT_LAYER_FOLDER

        return SLOT_LAYER_FOLDER[self.slot]


# ---------------------------------------------------------------------------
# Non-equippable scene layers (rendered behind/under the character).
# ---------------------------------------------------------------------------
BACKGROUND_KEYS: tuple[tuple[str, str], ...] = (
    ("alley_neon", "Rain-slick alley under buzzing kanji neon."),
    ("rooftop_zenith", "Helipad rooftop above a sleeping city grid."),
    ("sanctum_abyss", "Runed stone chamber lit by drifting will-o-wisps."),
)

BODY_KEYS: tuple[tuple[str, str], ...] = (
    ("base_street", "Athletic neutral stance — the default mannequin."),
    ("base_aegis", "Braced combat stance, weight forward."),
    ("base_male", "Male Rookie Hunter — athletic compression fit."),
    ("base_female", "Female Rookie Hunter — athletic stealth fit."),
    ("base_shadow", "Fledgling Shadow Soldier — dark ethereal aura."),
    ("base_vn_1", "Visual Novel Heroine — Fair Porcelain Skin"),
    ("base_vn_2", "Visual Novel Heroine — Warm Peach Skin"),
    ("base_vn_3", "Visual Novel Heroine — Golden Tan Skin"),
    ("base_vn_4", "Visual Novel Heroine — Sunlit Bronze Skin"),
    ("base_vn_5", "Visual Novel Heroine — Deep Cocoa Skin"),
)

# ---------------------------------------------------------------------------
# Equippable catalog
# ---------------------------------------------------------------------------
ITEMS: tuple[ItemDef, ...] = (
    # --- legs -------------------------------------------------------------
    ItemDef(
        id="street_slacks",
        name="Street Slacks",
        slot=Slot.LEGS,
        rarity=Rarity.COMMON,
        defense=2,
        drip=1,
        price_credits=120,
        shop_pool="permanent",
        description="Plain black slacks. Nobody looks twice.",
    ),
    ItemDef(
        id="combat_boots",
        name="Combat Boots",
        slot=Slot.LEGS,
        rarity=Rarity.COMMON,
        defense=4,
        drip=1,
        price_credits=260,
        shop_pool="permanent",
        description="Steel toe, loud on wet pavement.",
    ),
    ItemDef(
        id="techwear_cargo",
        name="Techwear Cargos",
        slot=Slot.LEGS,
        rarity=Rarity.RARE,
        defense=7,
        drip=4,
        price_credits=850,
        shop_pool="permanent",
        description="Nineteen pockets, one of them hums.",
    ),
    ItemDef(
        id="street_slides",
        name="Arcane Slides with Socks",
        slot=Slot.LEGS,
        rarity=Rarity.RARE,
        defense=3,
        drip=9,
        price_credits=700,
        description="Disrespectful. Effective. Dripping.",
    ),
    ItemDef(
        id="shadow_wargreaves",
        name="Shadow Wargreaves",
        slot=Slot.LEGS,
        rarity=Rarity.LEGENDARY,
        defense=16,
        drip=8,
        price_credits=3200,
        price_soul_shards=6,
        description="They step where light refuses to.",
    ),
    ItemDef(
        id="jeans_blue",
        name="شلوار جین کلاسیک آبی",
        slot=Slot.LEGS,
        rarity=Rarity.COMMON,
        defense=3,
        drip=3,
        price_credits=160,
        shop_pool="permanent",
        description="شلوار جین کلاسیک آبی با تن‌خور راحت و بادوام.",
    ),
    ItemDef(
        id="jeans_black",
        name="جین مشکی ذغالی راک",
        slot=Slot.LEGS,
        rarity=Rarity.COMMON,
        defense=4,
        drip=4,
        price_credits=240,
        shop_pool="permanent",
        description="جین ذغالی جذب با استایل خیابانی و دارک.",
    ),
    ItemDef(
        id="jeans_acid_wash",
        name="جین اسیدواش وینتیج",
        slot=Slot.LEGS,
        rarity=Rarity.RARE,
        defense=5,
        drip=7,
        price_credits=650,
        shop_pool="rotating",
        description="جین اسیدواش طرح‌دار الهام‌گرفته از مدهای دهه نود.",
    ),
    ItemDef(
        id="pants_leather_dark",
        name="شلوار چرم مشکی بایکری",
        slot=Slot.LEGS,
        rarity=Rarity.RARE,
        defense=7,
        drip=8,
        price_credits=850,
        shop_pool="rotating",
        description="چرم براق با دوخت تقویتی و مقاومت بالا.",
    ),
    ItemDef(
        id="slacks_white",
        name="شلوار کتان سفید تابستانه",
        slot=Slot.LEGS,
        rarity=Rarity.RARE,
        defense=4,
        drip=7,
        price_credits=590,
        shop_pool="rotating",
        description="کتان خنک و شیک مناسب استایل‌های مینیمال.",
    ),
    ItemDef(
        id="cargo_khaki",
        name="کارگو خاکی خیابانی",
        slot=Slot.LEGS,
        rarity=Rarity.COMMON,
        defense=5,
        drip=4,
        price_credits=340,
        shop_pool="permanent",
        description="شلوار جیب‌دار کاربردی و مقاوم در ماموریت‌های شهری.",
    ),
    ItemDef(
        id="skirt_pleated_navy",
        name="دامن پلیسه سرمه‌ای آکادمی",
        slot=Slot.LEGS,
        rarity=Rarity.COMMON,
        defense=2,
        drip=6,
        price_credits=280,
        shop_pool="permanent",
        description="دامن پلیسه کلاسیک یونیفرم دانش‌آموزی انیمه.",
    ),
    ItemDef(
        id="skirt_pleated_black",
        name="دامن پلیسه مشکی گوتیک",
        slot=Slot.LEGS,
        rarity=Rarity.RARE,
        defense=3,
        drip=8,
        price_credits=560,
        shop_pool="rotating",
        description="پلیسه مشکی مات با جلوه‌ای رازآلود و جذاب.",
    ),
    ItemDef(
        id="skirt_pleated_pink",
        name="دامن پلیسه صورتی پاستلی",
        slot=Slot.LEGS,
        rarity=Rarity.RARE,
        defense=2,
        drip=8,
        price_credits=580,
        shop_pool="rotating",
        description="استایل آیدلی ملایم و چشم‌نواز با رنگ پاستلی.",
    ),
    ItemDef(
        id="skirt_pleated_wine",
        name="دامن مخمل شرابی اشرافی",
        slot=Slot.LEGS,
        rarity=Rarity.EPIC,
        defense=5,
        drip=12,
        price_credits=1400,
        price_soul_shards=2,
        shop_pool="rotating",
        description="مخمل اشرافی دست‌دوز با درخشش قرمز تیره زیر نور مهتاب.",
    ),
    ItemDef(
        id="shorts_belted_denim",
        name="شلوارک جین کمربنددار",
        slot=Slot.LEGS,
        rarity=Rarity.COMMON,
        defense=2,
        drip=5,
        price_credits=260,
        shop_pool="permanent",
        description="شلوارک جین راحت با کمربند چرمی برای چابکی بالا.",
    ),
    ItemDef(
        id="shorts_belted_leather",
        name="شلوارک چرم سگک نقره‌ای",
        slot=Slot.LEGS,
        rarity=Rarity.RARE,
        defense=6,
        drip=9,
        price_credits=820,
        shop_pool="rotating",
        description="طراحی جسورانه با سگک‌های نقره‌ای صیقلی.",
    ),
    # --- body / tops ------------------------------------------------------
    ItemDef(
        id="fitted_tee",
        name="Fitted Tee",
        slot=Slot.BODY,
        rarity=Rarity.COMMON,
        defense=3,
        drip=2,
        price_credits=150,
        shop_pool="permanent",
        description="Cheap, clean, correct.",
    ),
    ItemDef(
        id="tactical_hoodie",
        name="Tactical Hoodie",
        slot=Slot.BODY,
        rarity=Rarity.RARE,
        defense=8,
        drip=3,
        price_credits=780,
        shop_pool="permanent",
        description="Reinforced elbows, silent zipper.",
    ),
    ItemDef(
        id="leather_bomber",
        name="Leather Bomber",
        slot=Slot.BODY,
        rarity=Rarity.RARE,
        defense=10,
        drip=5,
        price_credits=940,
        description="Scuffed at the shoulders. Worn in, not out.",
    ),
    ItemDef(
        id="hunter_trench",
        name="Hunter's Trench",
        slot=Slot.BODY,
        rarity=Rarity.EPIC,
        defense=15,
        drip=9,
        price_credits=2400,
        price_soul_shards=3,
        shop_pool="permanent",
        description="Floor-length, cut for movement. The silhouette reads threat.",
    ),
    ItemDef(
        id="void_cuirass",
        name="Void Cuirass",
        slot=Slot.BODY,
        rarity=Rarity.LEGENDARY,
        defense=24,
        drip=12,
        price_credits=5200,
        price_soul_shards=10,
        description="Lighter than fabric. Darker than the room.",
    ),
    ItemDef(
        id="tunic_casual_striped",
        name="تونیک راه‌راه کژوال اورسایز",
        slot=Slot.BODY,
        rarity=Rarity.COMMON,
        defense=3,
        drip=4,
        price_credits=190,
        shop_pool="permanent",
        description="تونیک راحت و آزاد با راه‌راه‌های مورب مدرن.",
    ),
    ItemDef(
        id="tunic_navy_urban",
        name="تونیک سرمه‌ای مدرن",
        slot=Slot.BODY,
        rarity=Rarity.COMMON,
        defense=4,
        drip=4,
        price_credits=230,
        shop_pool="permanent",
        description="پیراهن نخی سرمه‌ای خنک با تن‌خور راحت.",
    ),
    ItemDef(
        id="tee_emerald_street",
        name="تیشرت گرافیتی سبز زمردی",
        slot=Slot.BODY,
        rarity=Rarity.COMMON,
        defense=3,
        drip=5,
        price_credits=220,
        shop_pool="permanent",
        description="استایل خیابانی پرانرژی با رنگ سبز زمردی چشم‌نواز.",
    ),
    ItemDef(
        id="blouse_wine_casual",
        name="شومیز شرابی مجلسی",
        slot=Slot.BODY,
        rarity=Rarity.RARE,
        defense=4,
        drip=7,
        price_credits=620,
        shop_pool="rotating",
        description="شومیز ساتن لخت با رنگ شرابی گرم و باوقار.",
    ),
    ItemDef(
        id="crop_sport_black",
        name="کراپ‌تاپ ورزشی نایت‌فیت",
        slot=Slot.BODY,
        rarity=Rarity.RARE,
        defense=3,
        drip=8,
        price_credits=590,
        shop_pool="rotating",
        description="کراپ ورزشی مشکی چابک، الهام گرفته از رزمی‌کاران مدرن.",
    ),
    ItemDef(
        id="crop_sport_white",
        name="کراپ‌تاپ هانتر مینیمال سفید",
        slot=Slot.BODY,
        rarity=Rarity.RARE,
        defense=3,
        drip=7,
        price_credits=540,
        shop_pool="permanent",
        description="سفید مینیمال و آیرودینامیک با انعطاف‌پذیری فوق‌العاده.",
    ),
    ItemDef(
        id="cardigan_argyle_blue",
        name="کاردیگان چهارخانه کالج آبی",
        slot=Slot.BODY,
        rarity=Rarity.RARE,
        defense=6,
        drip=8,
        price_credits=790,
        shop_pool="rotating",
        description="بافت آرگایل دانشکده‌ای کلاسیک و شیک.",
    ),
    ItemDef(
        id="cardigan_argyle_wine",
        name="کاردیگان اشرافی زرشکی",
        slot=Slot.BODY,
        rarity=Rarity.EPIC,
        defense=8,
        drip=11,
        price_credits=1600,
        price_soul_shards=2,
        shop_pool="rotating",
        description="بافت سنگین و اعیانی برای شب‌های سرد پایتخت.",
    ),
    ItemDef(
        id="sweater_college_white",
        name="پلیور بافت کلاسیک آیوی‌لیگ",
        slot=Slot.BODY,
        rarity=Rarity.RARE,
        defense=7,
        drip=9,
        price_credits=880,
        shop_pool="rotating",
        description="پلیور سفید کرم ضخیم و باپرستیژ دانشگاهی.",
    ),
    ItemDef(
        id="blouse_offshoulder_white",
        name="بلوز ابریشمی یقه‌قایقی سفید",
        slot=Slot.BODY,
        rarity=Rarity.EPIC,
        defense=6,
        drip=13,
        price_credits=1850,
        price_soul_shards=3,
        shop_pool="rotating",
        description="طراحی دکلته ابریشمی که وقار و ظرافت رو فریاد می‌زنه.",
    ),
    ItemDef(
        id="blouse_offshoulder_black",
        name="بلوز توری مشکی مهمانی شب",
        slot=Slot.BODY,
        rarity=Rarity.EPIC,
        defense=7,
        drip=14,
        price_credits=2100,
        price_soul_shards=3,
        shop_pool="rotating",
        description="پارچه دانتل مشکی خیره‌کننده با خطوط دوخت ظریف.",
    ),
    ItemDef(
        id="blouse_offshoulder_wine",
        name="شومیز دکلته مخمل سلطنتی",
        slot=Slot.BODY,
        rarity=Rarity.LEGENDARY,
        defense=12,
        drip=18,
        price_credits=4800,
        price_soul_shards=8,
        shop_pool="rotating",
        description="جذابیت اشرافی خالص؛ برازنده‌ی قهرمانان تراز اول.",
    ),
    ItemDef(
        id="vest_urban_denim",
        name="وست جین دولایه استریت‌ویر",
        slot=Slot.BODY,
        rarity=Rarity.RARE,
        defense=9,
        drip=9,
        price_credits=950,
        shop_pool="rotating",
        description="جلیقه جین سنگین با جیب‌های متعدد برای ماجراجویی شهری.",
    ),
    ItemDef(
        id="vest_urban_black",
        name="وست چرمی تاکتیکال شادو",
        slot=Slot.BODY,
        rarity=Rarity.EPIC,
        defense=14,
        drip=12,
        price_credits=2400,
        price_soul_shards=4,
        shop_pool="rotating",
        description="چرم مسلح تقویت‌شده با الیاف ضدضربه برای نبردهای سنگین.",
    ),
    # --- head / hair ------------------------------------------------------
    ItemDef(
        id="street_fade",
        name="Street Fade",
        slot=Slot.HEAD,
        rarity=Rarity.COMMON,
        drip=2,
        price_credits=90,
        shop_pool="permanent",
        description="Sharp line, sharper confidence.",
    ),
    ItemDef(
        id="hood_up",
        name="Hood Up",
        slot=Slot.HEAD,
        rarity=Rarity.RARE,
        defense=2,
        drip=4,
        price_credits=520,
        description="Half your face gone. Whole your attitude stays.",
    ),
    ItemDef(
        id="raven_shag",
        name="Raven Shag",
        slot=Slot.HEAD,
        rarity=Rarity.EPIC,
        drip=7,
        price_credits=1600,
        price_soul_shards=2,
        description="Black hair that moves like it has opinions.",
    ),
    ItemDef(
        id="crown_of_shadows",
        name="Crown of Shadows",
        slot=Slot.HEAD,
        rarity=Rarity.LEGENDARY,
        drip=14,
        atk=3,
        price_credits=4200,
        price_soul_shards=8,
        description="Nobody crowns you. You just start glowing.",
    ),
    ItemDef(
        id="hair_waves_blonde",
        name="گیسوان موج‌دار بلوند پلاتینیوم",
        slot=Slot.HEAD,
        rarity=Rarity.COMMON,
        drip=5,
        price_credits=150,
        shop_pool="permanent",
        description="موی بلند و پرپشت مواج با تناژ پلاتینیوم درخشان.",
    ),
    ItemDef(
        id="hair_waves_black",
        name="موی بلند مواج مشکی کلاغی",
        slot=Slot.HEAD,
        rarity=Rarity.COMMON,
        drip=5,
        price_credits=150,
        shop_pool="permanent",
        description="گیسوان ابریشمی مشکی خیره‌کننده با موج‌های طبیعی.",
    ),
    ItemDef(
        id="hair_waves_silver",
        name="آبشار نقره‌ای مهتابی",
        slot=Slot.HEAD,
        rarity=Rarity.RARE,
        drip=9,
        price_credits=680,
        shop_pool="rotating",
        description="موی بلند نقره‌ای شفاف با حال و هوای قهرمانان مانهوا.",
    ),
    ItemDef(
        id="hair_waves_purple",
        name="گیسوان آمتیست بنفش سایه",
        slot=Slot.HEAD,
        rarity=Rarity.EPIC,
        drip=13,
        price_credits=1750,
        price_soul_shards=2,
        shop_pool="rotating",
        description="موی بنفش سلطنتی تیره با انعکاس نور تاریکی.",
    ),
    ItemDef(
        id="hair_bob_black",
        name="مدل باب کوتاه لخت مشکی",
        slot=Slot.HEAD,
        rarity=Rarity.COMMON,
        drip=4,
        price_credits=120,
        shop_pool="permanent",
        description="برش تمیز و زاویه‌دار با چتری‌های صاف روی پیشانی.",
    ),
    ItemDef(
        id="hair_bob_brunette",
        name="مدل باب شاه‌بلوطی ابریشمی",
        slot=Slot.HEAD,
        rarity=Rarity.COMMON,
        drip=4,
        price_credits=120,
        shop_pool="permanent",
        description="رنگ قهوه‌ای شکلاتی با براقیت طبیعی و استایل دخترانه.",
    ),
    ItemDef(
        id="hair_bob_silver",
        name="مدل باب سایبرنتیک نقره‌ای",
        slot=Slot.HEAD,
        rarity=Rarity.RARE,
        drip=8,
        price_credits=620,
        shop_pool="rotating",
        description="استایل آینده‌نگرانه و مینیمال با رنگ نقره‌ای یخی.",
    ),
    ItemDef(
        id="hair_twintails_blonde",
        name="موهای خرگوشی بلوند پرانرژی",
        slot=Slot.HEAD,
        rarity=Rarity.RARE,
        drip=8,
        price_credits=590,
        shop_pool="rotating",
        description="دوگوشی‌های بلند و بازیگوش با موج‌های پرپشت بلوند.",
    ),
    ItemDef(
        id="hair_twintails_pink",
        name="موهای خرگوشی صورتی آیدل",
        slot=Slot.HEAD,
        rarity=Rarity.EPIC,
        drip=14,
        price_credits=1950,
        price_soul_shards=3,
        shop_pool="rotating",
        description="استایل سوپراستارهای پاپ و انیمه با رنگ صورتی رویایی.",
    ),
    ItemDef(
        id="hair_bun_black",
        name="گوجه‌ای کلاسیک اشرافی مشکی",
        slot=Slot.HEAD,
        rarity=Rarity.COMMON,
        drip=4,
        price_credits=130,
        shop_pool="permanent",
        description="شینیون مرتب و جمع در بالای سر؛ باوقار و آماده نبرد.",
    ),
    ItemDef(
        id="hair_bun_silver",
        name="شینیون سلطنتی نقره‌ای",
        slot=Slot.HEAD,
        rarity=Rarity.RARE,
        drip=9,
        price_credits=720,
        shop_pool="rotating",
        description="گوجه‌ای شیک نقره‌ای با تار موهای ظریف رها شده دور صورت.",
    ),
    ItemDef(
        id="hair_pixie_black",
        name="مدل پیکسی چابک مشکی",
        slot=Slot.HEAD,
        rarity=Rarity.COMMON,
        drip=4,
        price_credits=110,
        shop_pool="permanent",
        description="موی خیلی کوتاه، سبک و بدون دردسر برای رزمی‌کاران سریع.",
    ),
    ItemDef(
        id="hair_pixie_silver",
        name="پیکسی قهرمان نقره‌ای مانهوا",
        slot=Slot.HEAD,
        rarity=Rarity.RARE,
        drip=10,
        price_credits=780,
        shop_pool="rotating",
        description="موی کوتاه خرد شده با تارهای تیز و درخشان نقره‌ای.",
    ),
    ItemDef(
        id="hair_pixie_blue",
        name="پیکسی نئونی آبی کهکشانی",
        slot=Slot.HEAD,
        rarity=Rarity.EPIC,
        drip=13,
        price_credits=1800,
        price_soul_shards=2,
        shop_pool="rotating",
        description="رنگ آبی الکتریکی براق الهام گرفته از قدرت‌های جادویی.",
    ),
    # --- accessory / face -------------------------------------------------
    ItemDef(
        id="tactical_goggles",
        name="Tactical Goggles",
        slot=Slot.ACCESSORY,
        rarity=Rarity.COMMON,
        defense=2,
        drip=2,
        price_credits=220,
        shop_pool="permanent",
        description="Amber lenses. Data lives in them.",
    ),
    ItemDef(
        id="half_mask",
        name="Ceramic Half-Mask",
        slot=Slot.ACCESSORY,
        rarity=Rarity.RARE,
        defense=4,
        drip=6,
        price_credits=690,
        description="Breathes easy. Says nothing.",
    ),
    ItemDef(
        id="arcane_eye_mark",
        name="Arcane Eye Marking",
        slot=Slot.ACCESSORY,
        rarity=Rarity.EPIC,
        atk=6,
        drip=8,
        price_credits=2100,
        price_soul_shards=3,
        description="A glyph under the left eye that reads your intent.",
    ),
    ItemDef(
        id="phantom_visage",
        name="Phantom Visage",
        slot=Slot.ACCESSORY,
        rarity=Rarity.LEGENDARY,
        atk=5,
        defense=6,
        drip=15,
        price_credits=5400,
        price_soul_shards=12,
        description="The face you had before the city took it.",
    ),
    # --- weapon -----------------------------------------------------------
    ItemDef(
        id="police_baton",
        name="Retired Baton",
        slot=Slot.WEAPON,
        rarity=Rarity.COMMON,
        atk=6,
        price_credits=180,
        shop_pool="permanent",
        description="Evidence locker, unofficially.",
    ),
    ItemDef(
        id="combat_knife",
        name="Tactical Combat Knife",
        slot=Slot.WEAPON,
        rarity=Rarity.COMMON,
        atk=11,
        price_credits=430,
        shop_pool="permanent",
        description="Nine inches of conversation ender.",
    ),
    ItemDef(
        id="neon_sai",
        name="Neon Sai",
        slot=Slot.WEAPON,
        rarity=Rarity.RARE,
        atk=18,
        drip=3,
        price_credits=1150,
        description="Glows cyan. Hums at low frequency.",
    ),
    ItemDef(
        id="shadow_katana",
        name="Shadow Katana",
        slot=Slot.WEAPON,
        rarity=Rarity.EPIC,
        atk=31,
        drip=6,
        price_credits=3400,
        price_soul_shards=5,
        shop_pool="permanent",
        description="Drawn from a scabbard that isn't there.",
    ),
    ItemDef(
        id="arcane_gauntlet",
        name="Arcane Gauntlet",
        slot=Slot.WEAPON,
        rarity=Rarity.LEGENDARY,
        atk=47,
        defense=8,
        drip=10,
        price_credits=6800,
        price_soul_shards=14,
        description="Closes around your fist and starts deciding.",
    ),
    # --- aura -------------------------------------------------------------
    ItemDef(
        id="ethereal_smoke",
        name="Ethereal Smoke",
        slot=Slot.AURA,
        rarity=Rarity.RARE,
        drip=6,
        price_credits=900,
        shop_pool="permanent",
        description="Curls off the shoulders like the street is smouldering.",
    ),
    ItemDef(
        id="lightning_crackle",
        name="Lightning Crackle",
        slot=Slot.AURA,
        rarity=Rarity.EPIC,
        atk=8,
        drip=9,
        price_credits=2600,
        price_soul_shards=4,
        description="Static in the teeth, ozone in the coat.",
    ),
    ItemDef(
        id="dark_flame",
        name="Dark Flame",
        slot=Slot.AURA,
        rarity=Rarity.LEGENDARY,
        atk=14,
        defense=6,
        drip=16,
        price_credits=5800,
        price_soul_shards=15,
        shop_pool="permanent",
        description="Fire that only ever consumes one thing.",
    ),
)

ITEMS_BY_ID: dict[str, ItemDef] = {item.id: item for item in ITEMS}


def starter_kit_ids() -> tuple[str, ...]:
    """Item ids every newly created player is given, so /me renders a full look."""
    return ("street_slacks", "fitted_tee", "street_fade")


def art_specs() -> list[tuple[str, str]]:
    """Every (layer_folder, layer_key) PNG the asset generator must produce."""
    specs: list[tuple[str, str]] = []
    specs.extend(("backgrounds", key) for key, _ in BACKGROUND_KEYS)
    specs.extend(("body", key) for key, _ in BODY_KEYS)
    specs.extend((item.folder, item.layer_key) for item in ITEMS)
    return specs


def art_descriptions() -> dict[tuple[str, str], str]:
    """Human-readable caption per art spec (used to seed the catalog + docs)."""
    out: dict[tuple[str, str], str] = {
        ("backgrounds", key): desc for key, desc in BACKGROUND_KEYS
    }
    out.update({("body", key): desc for key, desc in BODY_KEYS})
    out.update({(item.folder, item.layer_key): item.description for item in ITEMS})
    return out
